### ISSUE TITLE
Impossible to make it past "Cave Entrance"

### ISSUE THREAD

**Issue by notlinuxpeng** [HPL-Team/Project-HPL#8]
Sea Outpost requires the "Wave Drill," "Craside Brewer," and "Repair Turret" items, but they are unobtainable as the resources necessary to make them are not present on Cave Entrance. This makes it impossible to progress campaign gameplay.

Another issue is the way some things are designed. Typical Mindustry levels should have mines close to the enemy in waved sectors, so you can set up resources there. Not only this, but the fact that the enemies in Cave Entrance spawn very far away, so you need to set defense around your core, which if you've played Mindustry past Frozen Forest, you would know is an absolutely terrible idea and incredibly awkward to execute.

The third and final issue is that there are minable Fors that should be able to be mined by normal drills (i.e; Mechanical, Pneumatic, Laser, and Airblast drills), but there are no unlocks that let you mine them with anything except your core unit. This was very likely designed for drill use, but they weren't added, making resources scarce and hard to collect, which in turn greatly decreases the quality.

Issues aside, I loved the art and concepts this mod brings. There are just a few things to work out :)

**Comment by m1ss1onBest** [comment]
Thx for noticing that.

- Since Fors is extracted from large 2х2 ore blocks, player needs a way to get it without anything, we decided to add normal ores (I think all ores should be 2x2 blocks, or make another unique type of ore and have 2 types of ores, in next updates).
- I'll remake all the sectors in the v0.3 update *(content balancing included)*.
All fixes in next updates

**Comment by notlinuxpeng** [comment]
Nevermind, it just so happens that Volcanic serrid is required to unlock the Craside Brewer.

There is no indication it is minable, so I didn't notice it. You should add it into the tutorial :D

**Comment by m1ss1onBest** [comment]
Yeah, I remember, we wanted the player to get the first serrid without any drills and then research the drill later. Now I'm not sure how good of an idea this is. Anyway, I have an idea how to make it better

**Comment by carlosepcc** [comment]
OH! Wow. Thanks! I came here because I went stuck also by the Volcanic serrid. And now I started to click every floor in search for it. 

Listen, I **ENJOYED** A **LOT** the campaign so far (I've just made it to Cave Entrance). I think the scarcity of the resources made me enjoy it more as I had to plan the use and what structures to prioritize, I enjoyed losing the first time, so I could realize that this mod wasn't like the others, If it were, I would have bored me with the same technique of drills etc, but this is the first one I see that leverages the core unit's ability to mine (even if it's because it is incomplete)

I found myself mining a lot in order to build and pressing the [E] key to toggle between mining and building and I LOVED IT! also I had to use the core unit to shoot some times and  It just felt like the core unit got more protagonism. 

Maybe by accident, you gave the game a new fresh experience and difficulty not based on enemy units amount or strength and I don't want to lose it if that's what you intend.

One think I couldn't figure out is the purpose of the Plasma node. Is it still in development? I only used Plasma Distributors.

Another thing I liked is the environment and the glowing destructible rocks and minerals one cannot mine.

I didn't like that once you capture the sector, there is nothing interesting in some of the enemy spawn area. I need a reward! even if it doesn't help that much, al least an ore, or a more beautiful environment there or a strange structure made of walls...

After all this, THANKS! 
I'm hoping to develop my own mod inspired in StarCraft




[UPDATE]
Now I researched and build a Wave drill and just remembered there was a strange derelict Drill I destroyed, and found apparently nothing in the place it was at. 
I just didn't think of trying to mine "barehands" 
I think the idea is very good, but that is us who are not used to have to think and explore with curiosity to see if one can discover something. We are used to have all there, with vibrant different colors.

Just something must be made in this mod to leave clear to the user how to mine it if it gets stuck. Maybe after capturing the sector, there thing that is in the enemy spawn area is a network of derelict Wave Drills and old broken conveyor lines on top of huita rock and some Volcanic serrid in the conveyors so one can see it, wonder, take it and unlock the content in the tech tree.

**Comment by m1ss1onBest** [comment]
Thank you for the feedback! It's very nice to see reviews like this.
The mod is still in development and a lot of things may change (items, blocks, units, maps, etc).
About the plasma nodes, they're should complicate the gameplay a little, also all the content will be rebalanced in next updates.
Since I'm completely remaking the environment, the maps will also be redone.
Just waiting for the next update, everything will be...
